"use client";

import { useEffect, useLayoutEffect, useRef, useState, type FormEvent } from 'react';
import { gsap } from 'gsap';
import { usePageMotion } from '@/lib/use-page-motion';
import { LearningPhotos, ParallaxGallery, StoryPhoto } from '@/components/scroll-photos';
import { ArrowUpRight, ArrowRight, ArrowDown, Sun, Sprout, Heart, Blocks, BookOpen, MessageCircle, Menu, MapPin, Phone, Mail, Send, Check, Sparkles, Hand, Shapes, Footprints, Users, X } from 'lucide-react';
import { Tabs, TabsList, TabsTrigger, TabsContent } from '@/components/ui/tabs';
import { Accordion, AccordionItem, AccordionTrigger, AccordionContent } from '@/components/ui/accordion';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Sheet, SheetContent, SheetTitle, SheetDescription } from '@/components/ui/sheet';

const programmes = [
 {name:'Playgroup',eyebrow:'THE JOY OF FIRST DISCOVERIES',title:'A little world of wonder.',text:'A gentle introduction to learning beyond home. Children explore materials, enjoy stories and movement, and begin discovering the joy of learning alongside others.',items:['Sensory exploration','Everyday independence','Language through play'],icon:Sprout},
 {name:'Nursery',eyebrow:'CURIOSITY TAKES ROOT',title:'So many things to explore.',text:'Purposeful play gives growing curiosity a direction. Hands-on activities introduce early language and number ideas while encouraging children to make choices and try for themselves.',items:['Hands-on number ideas','Stories and phonics','Friendship and expression'],icon:Blocks},
 {name:'LKG',eyebrow:'CONFIDENCE IN EVERY STEP',title:'Small steps. Growing confidence.',text:'Children build on their discoveries through meaningful language, numeracy and group experiences, with space to ask questions, think independently and develop new skills.',items:['Language and early writing','Patterns and problem-solving','Learning together'],icon:BookOpen},
 {name:'UKG',eyebrow:'READY FOR WHAT COMES NEXT',title:'A bright beginning, beyond preschool.',text:'Growing readers, thinkers and communicators deepen their understanding through purposeful activities. We nurture the confidence and independence to take their next learning steps.',items:['Developing reading and writing','Exploring the world','Confidence and independence'],icon:Sun}
];
const faqs = [
 {q:'What programmes do you offer?',a:'We offer Playgroup, Nursery, LKG and UKG. Our team can help you choose the right starting point for your child. Please contact us to confirm age eligibility and current availability.',keys:['program','class','age','playgroup','nursery','lkg','ukg']},
 {q:'How do children learn at Prana Gurukul?',a:'Our Montessori-inspired approach combines purposeful play, hands-on Kreedo materials and teacher guidance. Children learn through exploration, stories, role-play, movement and small-group activities.',keys:['learn','montessori','curriculum','kreedo','teach','method','approach']},
 {q:'How do you follow my child’s progress?',a:'Teachers observe children every day and note their progress. Simple assessments help guide learning rather than placing the focus on formal exams. We also welcome parent feedback and share guidance for learning at home.',keys:['progress','test','exam','assess','growth','parent','home']},
 {q:'What are the fees and school timings?',a:'Please speak with our admissions team on 9900166733 for current fees, school timings and admission details. These can vary by programme and are best confirmed directly with the school.',keys:['fee','cost','price','timing','hour','admission','seat','2027']},
 {q:'Do you offer transport or daycare?',a:'Please call 9900166733 to confirm whether transport or daycare is available for your family. These services are not confirmed in our prospectus.',keys:['transport','bus','daycare','day care','food','meal','safety','cctv']},
 {q:'How can we visit the preschool?',a:'You can call 9900166733 or use “Plan a visit” to prepare an email request. Find us at 1742, Block 2, Banashankari Stage 6, Kariyana Palya, Bengaluru 560062. The school will confirm your visit time.',keys:['visit','book','location','address','where','contact','phone','email','direction']}
];
const areas = [
 {icon:Footprints,title:'Move with confidence',text:'Balance, coordination and the joy of movement.',color:'peach'},
 {icon:Shapes,title:'Think & discover',text:'Patterns, questions and new ways to solve problems.',color:'sage'},
 {icon:MessageCircle,title:'Find their voice',text:'Stories, conversations and growing language skills.',color:'yellow'},
 {icon:Hand,title:'Explore the senses',text:'Shapes, textures and learning through doing.',color:'yellow'},
 {icon:Heart,title:'Feel & connect',text:'Friendship, kindness and understanding emotions.',color:'peach'},
 {icon:Blocks,title:'Make numbers meaningful',text:'Counting, sorting and early mathematical ideas.',color:'sage'}
];
const scenes = [
 {word:'Explore.',label:'01 / A LITTLE CURIOSITY',text:'A colour catches their eye. A shape feels new. Learning begins with the freedom to wonder.',caption:'Room to choose. Space to discover.',position:'50% 32%'},
 {word:'Try.',label:'02 / A LITTLE COURAGE',text:'A block balances. A tower tumbles. Trying again turns small discoveries into real understanding.',caption:'Little hands, learning by doing.',position:'50% 80%'},
 {word:'Grow.',label:'03 / A LITTLE MORE CONFIDENCE',text:'With a caring teacher nearby, “Can I?” becomes “I did it!” And a love of learning begins to bloom.',caption:'Every little step deserves to be noticed.',position:'50% 43%'}
];
const directions='https://maps.app.goo.gl/GQXBVfbK7GZvwmv47'

function Brand(){return <a href="#home" className="brand" aria-label="Prana Gurukul home"><img src="/Prana.png" alt="Prana Gurukul Logo" width="108" height="68"/><span>Prana Gurukul<small>P R E S C H O O L</small></span></a>}
function Wave(){return <svg className="underline" viewBox="0 0 340 20" fill="none" aria-hidden="true"><path d="M3 12C75 1 168 1 337 9M38 18C130 7 250 9 310 14" stroke="currentColor" strokeWidth="3" strokeLinecap="round"/></svg>}

export default function Home(){
 const [visit,setVisit]=useState(false),[chat,setChat]=useState(false),[menu,setMenu]=useState(false),[input,setInput]=useState(''),[scene,setScene]=useState(0),[draft,setDraft]=useState('');
 const [messages,setMessages]=useState([{role:'bot',text:'Hello! I’m Prana’s virtual guide. Ask me about programmes, learning or visiting our preschool.'}]);
 const page=useRef<HTMLDivElement>(null), story=useRef<HTMLElement>(null), end=useRef<HTMLDivElement>(null);
 usePageMotion(page, setScene);
 useLayoutEffect(()=>{
  const media=gsap.matchMedia();
  media.add('(prefers-reduced-motion: no-preference)',()=>{
   gsap.from('.scene-copy', {opacity:0,y:18,duration:0.55,ease:'power2.out',clearProps:'all'});

  }, story);
  return ()=>media.revert();
 },[scene]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:window.matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'})},[messages]);
 function ask(question:string){const q=question.trim();if(!q)return;const normalized=q.toLowerCase();let answer='I don’t have a confirmed answer to that yet. Please call our school team on 9900166733 or email info@pranagurukul.com. I can also help with programmes, our learning approach and visits.';if(/^(hi|hello|hey|namaste)[!. ]*$/.test(normalized))answer='Hello! What would you like to know about Prana Gurukul? Try “What programmes do you offer?” or “How can I visit?”';else{const match=faqs.map(f=>({f,score:f.keys.filter(k=>normalized.includes(k)).length})).sort((a,b)=>b.score-a.score)[0];if(match.score>0)answer=match.f.a}setMessages(m=>[...m,{role:'user',text:q},{role:'bot',text:answer}]);setInput('')}
 function makeDraft(e:FormEvent<HTMLFormElement>){e.preventDefault();const d=new FormData(e.currentTarget);const body=`Hello Prana Gurukul,\n\nI would like to arrange a school visit.\n\nParent name: ${d.get('name')}\nPhone: ${d.get('phone')}\nProgramme of interest: ${d.get('programme')}\nPreferred date: ${d.get('date')||'Please suggest a suitable date'}\n\nPlease contact me to confirm a suitable time.\nThank you.`;setDraft('mailto:info@pranagurukul.com?subject='+encodeURIComponent('School visit enquiry')+'&body='+encodeURIComponent(body))}
 const openVisit=()=>{setDraft('');setVisit(true)};
 return <div ref={page}>
  <a className="skip" href="#main">Skip to content</a><div className="reading-progress" aria-hidden="true"/>
  <div className="announcement"><span>A joyful beginning. A world of possibilities.</span><button onClick={openVisit}>Come meet us <ArrowUpRight size={14}/></button></div>
  <header><div className="nav-wrap"><Brand/><nav aria-label="Main navigation"><a href="#approach">Our approach</a><a href="#programmes">Programmes</a><a href="#our-world">Our world</a><a href="#questions">Parent FAQs</a></nav><button className="button small desktop-visit" onClick={openVisit}>Plan a visit <ArrowUpRight size={17}/></button><button className="menu-button" aria-label="Open navigation" aria-expanded={menu} onClick={()=>setMenu(true)}><Menu/></button></div></header>
  <main id="main">
   <section className="hero wrap" id="home"><div className="hero-copy"><div className="eyebrow"><span/> A LITTLE BEGINNING. A LIFETIME OF WONDER.</div><h1>Little minds.<br/>Beautiful<br/><em>beginnings.<Wave/></em></h1><p>A place to wonder, discover and grow.<br className="desktop-break"/> Hands-on learning and heartfelt care, at your child’s own pace.</p><div className="hero-actions"><button className="button" onClick={openVisit}>Come discover Prana <ArrowUpRight size={19}/></button><a className="text-link" href="#our-world">Step into our world <ArrowRight size={17}/></a></div><div className="location"><MapPin size={16}/> Banashankari 6th Stage, Bengaluru</div></div><div className="hero-visual"><div className="image-arch"><img src="/images/little-discoveries.webp" width="1086" height="1448" fetchPriority="high" alt="A child exploring colourful wooden blocks at Prana Gurukul"/></div><div className="round-note"><Sun size={32}/><span>Small steps.<br/><b>Big discoveries.</b></span></div><div className="photo-note"><span className="tiny-line"/> Learning, one little discovery at a time.</div><span className="hero-number">01 — THE WONDER YEARS</span></div><a className="scroll-cue" href="#approach"><ArrowDown size={17}/> A little scroll, a little wonder</a></section>
   <div className="values-strip"><span><Sprout/> Montessori-inspired</span><span><Hand/> Hands-on learning</span><span><Heart/> Every child, their own pace</span><span><Sun/> Joy in the everyday</span></div>
   <section id="approach" className="intro wrap section reveal"><div className="eyebrow">ROOTED IN CARE. GROWING WITH CURIOSITY.</div><h2>Childhood is not a race.<br/>It’s a beautiful <em>discovery.</em></h2><div className="intro-bottom"><div className="intro-mark"><Sparkles size={44} strokeWidth={1.2}/><span>Room to wonder.<br/>Freedom to grow.</span></div><div><p>At Prana Gurukul, we see the possibility in every little question. Our Montessori-inspired approach brings together purposeful play, thoughtfully chosen materials and teachers who know when to guide — and when to let discovery happen.</p><p className="muted">Because a love of learning starts with the joy of doing.</p></div></div></section>
   <section id="our-world" className="story" ref={story}><div className="story-sticky"><div className="story-text"><div className="eyebrow">A PEEK INTO THEIR WORLD</div><div className="story-count">{scenes[scene].label}</div><div className="scene-copy" key={scene}><h2>{scenes[scene].word}</h2><p>{scenes[scene].text}</p></div><div className="story-indicators" aria-label="Learning story"><span className={scene===0?'active':''}>01</span><i/><span className={scene===1?'active':''}>02</span><i/><span className={scene===2?'active':''}>03</span></div><span className="story-instruction">A little more discovery with every scroll <ArrowDown size={16}/></span></div><div className="story-photo">{scenes.map((s,i)=><div className={`story-image-layer ${scene===i?'is-active':''}`} key={s.word} aria-hidden={scene!==i}><StoryPhoto index={i} alt={s.caption}/></div>)}<div className="story-caption"><Sparkles size={21}/>{scenes[scene].caption}</div></div></div><div className="mobile-story-notes"><div className="eyebrow">A PEEK INTO THEIR WORLD</div>{scenes.map((s,i)=><article key={s.word}><span className="eyebrow">{s.label}</span><h3>{s.word}</h3><p>{s.text}</p><figure className="mobile-story-photo"><StoryPhoto index={i} alt={s.caption}/><figcaption>{s.caption}</figcaption></figure></article>)}</div></section>
   <section className="section wrap" id="learning"><div className="section-heading reveal"><div><div className="eyebrow">GROWING IN EVERY WAY</div><h2>More than their<br/>first <em>ABCs.</em></h2></div><p>Six connected areas of learning.<br/>A whole world of possibilities.</p></div><div className="learning-layout"><LearningPhotos titles={areas.map(a=>a.title)}/><div className="learning-steps">{areas.map((a,i)=><article className={`area-card learning-step ${a.color}`} key={a.title}><div className="area-top"><a.icon strokeWidth={1.4} size={34}/><span>0{i+1}</span></div><h3>{a.title}</h3><p>{a.text}</p></article>)}</div></div></section>
   <ParallaxGallery/>
   <section className="programmes section" id="programmes"><div className="wrap"><div className="center-heading reveal"><div className="eyebrow">THEIR NEXT LITTLE STEP</div><h2>Growing up, <em>beautifully.</em></h2><p>Different beginnings. The same thoughtful care.</p></div><Tabs defaultValue="Playgroup" className="programme-tabs"><TabsList className="programme-list" aria-label="Preschool programmes">{programmes.map(p=><TabsTrigger key={p.name} value={p.name}>{p.name}</TabsTrigger>)}</TabsList>{programmes.map((p,i)=><TabsContent value={p.name} key={p.name} className="programme-content"><div className="programme-visual"><p>THE WONDER OF<br/><strong>{p.name}</strong></p><p.icon size={105} strokeWidth={.8} aria-hidden="true"/><span className="programme-index">0{i+1} / 04</span></div><div className="programme-copy"><div className="eyebrow">{p.eyebrow}</div><h3>{p.title}</h3><p>{p.text}</p><ul>{p.items.map(item=><li key={item}><Check size={17}/>{item}</li>)}</ul><button className="text-link" onClick={openVisit}>Let’s find their starting point <ArrowUpRight size={19}/></button></div></TabsContent>)}</Tabs><p className="programme-footnote">Every child’s journey is different. Our team will help you confirm age eligibility and the right programme.</p></div></section>
   <section className="care section wrap"><div className="care-heading reveal"><div className="eyebrow">GUIDED WITH HEART</div><h2>A little guidance.<br/>A lot of <em>belief.</em></h2><p>Behind every small discovery is a teacher who notices, encourages and cares.</p><button className="text-link" onClick={openVisit}>Come meet our team <ArrowUpRight size={18}/></button></div><div className="care-items"><article className="reveal"><span>01</span><div><h3>Close attention. Room to grow.</h3><p>Teachers support children in small groups, stepping in when needed and making space for independence.</p></div></article><article className="reveal"><span>02</span><div><h3>Little milestones, noticed.</h3><p>Everyday observation and simple assessments help teachers understand each child’s progress and guide their next steps.</p></div></article><article className="reveal"><span>03</span><div><h3>Growing together, beyond school.</h3><p>We welcome parent feedback and share guidance so that home and school can work together for your child.</p></div></article></div></section>
   <section className="philosophy-band"><div className="wrap"><BookOpen size={30} strokeWidth={1.3}/><p>Purposeful play. Thoughtful teaching.<br/><em>A lifelong love of learning.</em></p><span>THE PRANA GURUKUL WAY</span></div></section>
   <section className="faq-section section wrap" id="questions"><div className="faq-title reveal"><div className="eyebrow">FROM ONE CARING HEART TO ANOTHER</div><h2>Little questions.<br/><em>Thoughtful answers.</em></h2><p>Choosing their first school is a big step.<br/>We’re here to help.</p><button className="text-link" onClick={()=>setChat(true)}>Ask Prana a question <MessageCircle size={19}/></button></div><Accordion type="single" collapsible className="faq-list">{faqs.map((f,i)=><AccordionItem key={f.q} value={`faq-${i}`}><AccordionTrigger>{f.q}</AccordionTrigger><AccordionContent>{f.a}</AccordionContent></AccordionItem>)}</Accordion></section>
   <section id="visit" className="visit-section"><div className="wrap visit-inner"><div className="eyebrow">COME SAY HELLO</div><h2>Their next discovery<br/>could <em>begin here.</em></h2><p>Explore our learning spaces. Meet our team.<br/>Imagine the little possibilities.</p><button className="button light" onClick={openVisit}>Plan a school visit <ArrowUpRight size={20}/></button><a className="visit-call" href="tel:+919900166733">Or call us on 99001 66733</a><Sun className="visit-sun" size={150} strokeWidth={.65} aria-hidden="true"/></div></section>
  </main>
  <footer className="wrap"><div className="footer-top"><div><Brand/><p>Where little minds bloom bright.</p></div><div><span className="eyebrow">FIND OUR LITTLE WORLD</span><p>No.1743, Block 2, Ground Floor, Prana Gurukul Preschool, Street, Banashankari Stage 6,<br/> Kariyana Palya, Bengaluru, Karnataka 560062</p><a className="text-link" href={directions} target="_blank" rel="noreferrer">Get directions <ArrowUpRight size={16}/></a></div><div><span className="eyebrow">LET’S TALK</span><a href="tel:+919900166733">99001 66733</a><a href="mailto:info@pranagurukul.com">info@pranagurukul.com</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Prana Gurukul Preschool</span><a href="#home">Back to the beginning ↑</a><span>Made with care, for little futures.</span></div></footer>
  <button className="chat-launch" onClick={()=>setChat(true)}><MessageCircle size={21}/><span>Ask Prana</span></button><div className="mobile-bottom"><a href="tel:+919900166733"><Phone size={17}/>Call us</a><button onClick={openVisit}>Plan a visit <ArrowUpRight size={17}/></button></div>
  <Sheet open={menu} onOpenChange={setMenu}><SheetContent className="mobile-nav"><SheetTitle>Explore Prana</SheetTitle><SheetDescription>A little world of possibilities.</SheetDescription>{[['Our approach','approach'],['Programmes','programmes'],['Our world','our-world'],['Photo gallery','gallery'],['Parent FAQs','questions']].map(([label,id])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}<ArrowUpRight size={20}/></a>)}<button className="button" onClick={()=>{setMenu(false);openVisit()}}>Plan a visit <ArrowUpRight size={18}/></button></SheetContent></Sheet>
  <Dialog open={visit} onOpenChange={setVisit}><DialogContent className="visit-dialog"><DialogTitle>Come discover Prana.</DialogTitle><DialogDescription>Tell us a little about your visit. We’ll prepare an email for you to send to the school.</DialogDescription>{!draft?<form onSubmit={makeDraft} className="visit-form"><label>Your name<input name="name" required autoComplete="name" placeholder="Parent or guardian’s name" maxLength={100}/></label><label>Phone number<input name="phone" type="tel" required autoComplete="tel" pattern="[+0-9 ()-]{7,20}" placeholder="Your contact number"/></label><label>Programme of interest<input name="programme" placeholder="e.g. Nursery, or help me choose" maxLength={100}/></label><label>Preferred date <span>(optional)</span><input name="date" type="date" min={new Date().toLocaleDateString('en-CA')}/></label><p className="form-note">Your visit is confirmed only when the school replies. These details are used to compose your email and are not saved here.</p><button className="button" type="submit">Prepare visit request <ArrowRight size={18}/></button></form>:<div className="draft-ready"><Mail size={40}/><h3>Your request is ready.</h3><p>Open your email app, review the message and send it to the school. Prefer to talk? Call <a href="tel:+919900166733">99001 66733</a>.</p><a className="button" href={draft}>Open email to send <ArrowUpRight size={18}/></a><button className="text-link" onClick={()=>setDraft('')}>Edit details</button><p className="form-note">No email has been sent automatically.</p></div>}</DialogContent></Dialog>
  <Sheet open={chat} onOpenChange={setChat}><SheetContent className="chat-panel"><div className="chat-header"><span className="chat-icon"><Sprout size={26}/></span><div><SheetTitle>Ask Prana</SheetTitle><SheetDescription>Your preschool FAQ guide</SheetDescription></div></div><div className="chat-messages" role="log" aria-live="polite" aria-label="Conversation">{messages.map((m,i)=><div key={i} className={`message ${m.role}`}>{m.text}</div>)}<div ref={end}/></div><div className="quick-questions">{['Programmes','Fees & timings','Plan a visit'].map(q=><button key={q} onClick={()=>ask(q)}>{q}<ArrowUpRight size={13}/></button>)}</div><form className="chat-form" onSubmit={e=>{e.preventDefault();ask(input)}}><label className="sr-only" htmlFor="chat-input">Your question</label><input id="chat-input" value={input} onChange={e=>setInput(e.target.value)} placeholder="What would you like to know?" maxLength={500}/><button aria-label="Send question" disabled={!input.trim()}><Send size={19}/></button></form><p className="chat-note">Answers from our prospectus. For current admissions details, <a href="tel:+919900166733">call the school</a>.</p></SheetContent></Sheet>
 </div>
}
